package model;

import java.io.File;
import java.io.ByteArrayOutputStream;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.SourceDataLine;
/**
 * @author David Wakeling, Joshua Chalcraft
 *  - SoundPlayer class is used to play sound files.
 *  - It will either play sound files generated by SpeechGenerator or local files
 *  - The local files are error message sound files located in the res/errorMessages
 *  - These exceptions do not output local error sound files, as if this class doesn't work, then the outputted files won't play
 */
public class SoundPlayer
{
    private final static String FILENAME = "res/directions/sound_output.wav";

    /*
     * Set up stream.
     */
    private static AudioInputStream setupStream(String name)
    {
        try
        {
            File file = new File(name);
            AudioInputStream stm = AudioSystem.getAudioInputStream(file);
            return stm;
        }
        catch (Exception e)
        {
            System.out.println(e);
            return null;
        }
    }

    /*
     * Read stream.
     */
    private static ByteArrayOutputStream readStream(AudioInputStream stm)
    {
        try
        {
            AudioFormat af  = stm.getFormat();
            ByteArrayOutputStream bos = new ByteArrayOutputStream();

            int bufferSize = (int) af.getSampleRate() * af.getFrameSize();
            byte buffer[] = new byte[bufferSize];

            for ( ; ; )
            {
                int n = stm.read( buffer, 0, buffer.length );
                if ( n > 0 )
                {
                    bos.write( buffer, 0, n );
                }
                else
                {
                    break;
                }
            }
            return bos;
        }
        catch (Exception e)
        {
            System.out.println(e);
            return null;
        }
    }

    /*
     * Play stream.
     */
    private static void playStream( AudioInputStream stm, ByteArrayOutputStream bos )
    {
        try
        {
            AudioFormat    af   = stm.getFormat();
            byte[]         ba   = bos.toByteArray();
            DataLine.Info  info = new DataLine.Info(SourceDataLine.class, af);
            SourceDataLine line = (SourceDataLine) AudioSystem.getLine(info);

            line.open(af);
            line.start();
            line.write(ba, 0, ba.length);
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }


    /*
     * Uses the above methods to set up and play an audio file in one go.
     */
    public static void playDirection()
    {
        AudioInputStream stm = setupStream(FILENAME);
        playStream(stm, readStream(stm));
    }

    /*
     * Method designed to play files that diagnose errors or give the user more information
     * E.g. "recalculating".
     */
    public static void playFile(String file)
    {
        AudioInputStream stm = setupStream(file);
        playStream(stm, readStream(stm));
    }
}
